CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '0000';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'longview'@'localhost' IDENTIFIED BY '0000';
GRANT SELECT, PROCESS, SUPER ON *.* TO 'longview'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED BY '0000';
