# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, settings, ... }:
let
storage = import settings.storagePath{inherit settings;};
fileSystems = storage.fileSystems;
persistent = storage.persistent;
in{
environment.persistence.${settings.system.persistentStorage} = (persistent.system/* // {users.${settings.user.username}=persistent.user;}*/);
 inherit fileSystems;
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot = {
    initrd = { availableKernelModules = [ "xhci_pci" "usbhid" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "btrfs"]; kernelModules = [ "dm-snapshot" ]; };
    kernelParams = ["DP-2=1280x1024"];
    kernelModules = [ "kvm-intel" "i2c-dev" "i2c-piix4" "cpufreq_powersave"];
    extraModulePackages = [ ];
    supportedFilesystems = ["vfat" "ext4" "btrfs" "ntfs"];
    loader = { grub.useOSProber = true; efi.efiSysMountPoint = settings.system.bootMountPath; # does nothing if running bios rather than uefi
      };
  };


swapDevices = [ { device = "/dev/disk/by-label/NixSwap"; } ];
#   btrfs = { autoScrub = { enable = true; interval = "monthly"; fileSystems = [ "/Volume" ]; }; };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.graphics.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave"; #wasn't there by default
}
